import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='ru'>
      <body className={inter.className}>
        <div className='page'>
          <Header />
          <main className='main'>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
